//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M0502.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaludMovilEntities : DbContext
    {
        public SaludMovilEntities()
            : base("name=SaludMovilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sm_Estado> sm_Estado { get; set; }
        public virtual DbSet<sm_Poblacion> sm_Poblacion { get; set; }
        public virtual DbSet<sm_Programa> sm_Programa { get; set; }
    }
}
