//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M0502.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sm_Programa
    {
        public int idPrograma { get; set; }
        public string descripcion { get; set; }
        public int idEstado { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int poblacionObjetivo { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idRiesgoPrograma { get; set; }
    
        public virtual sm_Estado sm_Estado { get; set; }
        public virtual sm_Poblacion sm_Poblacion { get; set; }
    }
}
